In [2]:
import numpy as np

In [15]:
a = np.array([1,2,3], dtype="int16")
print(a)

[1 2 3]


In [6]:
b = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
# b.ndim
# b.shape
# a.dtype
# a.size
# a.itemsize
# a.nbytes

6

In [21]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [47]:
#get a specific element
# a[0,2]
#also
# a[0,-5]

#Get a Specific Row
# a[0, :]
#Get a Specific column
# a[:, 2]
#Getting a specific pieace[start:end:stepsize]
# a[0, 1: 6]
# a[1, 1 : -1 : 2 ]

array([5, 2])

In [13]:
import numpy as np
#to change something
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
# a[1, 5] = 20
# print(a)
#FOr multiple i.e entire sereis 
a[:,2] = [5,2]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  2 11 12 13 14]]


In [15]:
b = np.array([[[1,2],[3, 4]],[[5,6], [7,8,]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [48]:
#Get a specific element(work outside in)
b[1,1,1]


8

In [23]:
#replace 
b [:, 1, :]  = [[9,9],[8,8]]
print(b)


[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [24]:
#Initialize different types of array
#All 0's Matrixx
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [28]:
#All '1s matrix
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [32]:
#any other number
# np.full((3,3), 99)
#Full like already existed matrix
# np.full_like((a), 7)


array([[7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7]])

In [53]:
#For Random Numbers
# np.random.rand(2,2)
#For Float Numbers
# np.random.randint(-5, 3, size=(3,3))
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [58]:
arr =  np.array([[1,2,3]])
r1 = np.repeat(arr, 3 , axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [70]:
op = np.ones((5,5))
z  = np.zeros((3,3))
z[1,1]= 9
op[1:4,1:4]=z
print(op)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
